# Generated by Django 5.0.2 on 2025-10-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='last_activity',
            field=models.DateTimeField(auto_now=True, verbose_name='Последняя активность'),
        ),
    ]
