# Generated by Django 5.0.2 on 2025-09-03 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Основной заголовок раздела "О нас"', max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(help_text='Основной текст раздела "О нас"', verbose_name='Содержание')),
                ('image', models.ImageField(blank=True, help_text='Изображение для раздела "О нас"', null=True, upload_to='about/', verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=True, help_text='Показывать ли раздел на сайте', verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
                'ordering': ['-created_at'],
            },
        ),
    ]
