# Generated by Django 5.0.2 on 2025-09-03 03:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='content',
            field=ckeditor.fields.RichTextField(help_text='Основной текст раздела "О нас"', verbose_name='Содержание'),
        ),
    ]
