# Generated by Django 5.0.2 on 2025-07-10 17:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID сессии'),
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('session_id', 'user')},
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.CheckConstraint(check=models.Q(('session_id__isnull', False), ('user__isnull', False), _connector='OR'), name='cart_has_session_or_user'),
        ),
    ]
