# Generated by Django 5.0.2 on 2025-07-10 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_cart_session_id_alter_cart_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cart',
            name='cart_has_session_or_user',
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together=set(),
        ),
    ]
