# Generated by Django 5.0.2 on 2025-07-15 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_cart_cart_has_session_or_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер заказа'),
        ),
    ]
