# Generated by Django 5.2.1 on 2025-10-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='telegram_notification_sent',
            field=models.BooleanField(default=False, verbose_name='Telegram уведомления об отправке'),
        ),
    ]
