# Generated by Django 5.0.2 on 2026-06-30 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_guest_order_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='consent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата согласия на обработку ПД'),
        ),
        migrations.AddField(
            model_name='order',
            name='personal_data_consent',
            field=models.BooleanField(default=False, verbose_name='Согласие на обработку ПД'),
        ),
    ]
