# Generated by Django 5.0.2 on 2026-08-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_quote_request_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email_notification_sent',
            field=models.BooleanField(default=False, verbose_name='Email-уведомление отправлено'),
        ),
    ]
