# Generated by Django 5.0.2 on 2026-08-04 18:42

import catalog.image_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_card',
            field=models.ImageField(blank=True, help_text='Автоматически создаётся из основного фото (до ~800px, WebP).', null=True, upload_to=catalog.image_utils.card_upload_to, verbose_name='Превью для каталога'),
        ),
    ]
