# Generated by Django 5.0.2 on 2026-08-19 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_product_image_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availability_status',
            field=models.CharField(choices=[('in_stock', 'В наличии'), ('in_transit', 'В пути')], default='in_stock', help_text='«В наличии» — можно добавить в «Мои товары». «В пути» — только просмотр.', max_length=20, verbose_name='Статус наличия'),
        ),
    ]
