# Generated by Django 5.0.2 on 2026-06-30 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='personal_data_consent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата согласия на обработку ПД'),
        ),
    ]
