JAZZMIN_SETTINGS = {
    'site_title': 'Сказкин Дом',
    'site_header': 'Сказкин Дом',
    'site_brand': 'Сказкин Дом',
    'site_logo_classes': 'img-circle',
    'welcome_sign': 'Панель управления интернет-магазином',
    'copyright': 'Сказкин Дом',
    'search_model': [
        'catalog.Product',
        'catalog.Category',
        'orders.Order',
        'users.User',
        'news.News',
    ],
    'topmenu_links': [
        {'name': 'Открыть сайт', 'url': '/', 'new_window': True},
        {'name': 'API Swagger', 'url': '/swagger/', 'new_window': True},
    ],
    'usermenu_links': [
        {'name': 'API Swagger', 'url': '/swagger/', 'new_window': True},
    ],
    'show_sidebar': True,
    'navigation_expanded': True,
    'hide_apps': [],
    'hide_models': [],
    'order_with_respect_to': [
        'catalog',
        'orders',
        'users',
        'news',
        'about',
        'analytics',
        'notifications',
        'auth',
    ],
    'icons': {
        'auth': 'fas fa-users-cog',
        'auth.user': 'fas fa-user',
        'auth.Group': 'fas fa-users',
        'users.User': 'fas fa-user-circle',
        'catalog.Category': 'fas fa-folder',
        'catalog.Product': 'fas fa-couch',
        'orders.Order': 'fas fa-shopping-cart',
        'orders.Cart': 'fas fa-shopping-basket',
        'orders.Favorite': 'fas fa-heart',
        'news.News': 'fas fa-newspaper',
        'about.About': 'fas fa-info-circle',
        'analytics.ProductView': 'fas fa-chart-line',
        'analytics.SiteVisit': 'fas fa-globe',
    },
    'default_icon_parents': 'fas fa-chevron-circle-right',
    'default_icon_children': 'fas fa-circle',
    'related_modal_active': True,
    'custom_css': None,
    'custom_js': None,
    'use_google_fonts_cdn': True,
    'show_ui_builder': False,
    'changeform_format': 'horizontal_tabs',
    'changeform_format_overrides': {
        'catalog.Product': 'collapsible',
        'orders.Order': 'horizontal_tabs',
    },
}

JAZZMIN_UI_TWEAKS = {
    'navbar_small_text': False,
    'footer_small_text': False,
    'body_small_text': False,
    'brand_small_text': False,
    'brand_colour': 'navbar-primary',
    'accent': 'accent-primary',
    'navbar': 'navbar-white navbar-light',
    'no_navbar_border': False,
    'navbar_fixed': True,
    'layout_boxed': False,
    'footer_fixed': False,
    'sidebar_fixed': True,
    'sidebar': 'sidebar-dark-primary',
    'sidebar_nav_small_text': False,
    'sidebar_disable_expand': False,
    'sidebar_nav_child_indent': True,
    'sidebar_nav_compact_style': False,
    'sidebar_nav_legacy_style': False,
    'sidebar_nav_flat_style': False,
    'theme': 'flatly',
    'dark_mode_theme': None,
    'button_classes': {
        'primary': 'btn-primary',
        'secondary': 'btn-secondary',
        'info': 'btn-info',
        'warning': 'btn-warning',
        'danger': 'btn-danger',
        'success': 'btn-success',
    },
}
